name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # 使用你的默认分支名称
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 R 环境
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 安装系统依赖
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

      # 安装 R 包依赖
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("blogdown", "rmarkdown", "knitr", "yaml"))'

      # 安装 Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # 构建网站
      - name: Build site
        run: |
          Rscript -e 'blogdown::build_site()'

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
